name: "Update Tagged Releases"
on:
  push:

jobs:
  refresh-modules:
    name: Refresh Release Submodules
    runs-on: ubuntu-latest
    outputs:
      repo-matrix: ${{ steps.submodules.outputs.repos }}
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: releases
        submodules: recursive
    - name: Get submodules
      id: submodules
      run: |
        gitlines=$(git config --file .gitmodules --get-regexp path | awk '{ print $2 }')
        input=$(tr -s '[:blank:]' ',' < $gitlines)
        echo $input
        echo "::set-output name=repos:: [$input]"

  get-releases:
    name: Test releases
    runs-on: ubuntu-latest
    needs: ["refresh-modules"]

    strategy:
      fail-fast: false
      matrix:
        submodules: ${{needs.refresh-modules.outputs.repos}}

    steps:
    - id: versions
      uses: wistefan/get-releases-by-semver@master
      with:
        versionField: "TAG-NAME"
        repository: ${{ matrix.submodules }}

    - id: print
      run: |
        echo "Releases for ${{ matrix.submodules }}"
        echo "${{steps.versions.outputs.releases}}"
    
   
   
   
