name: "Update Tagged Releases"
on:
  push:

jobs:
  get-containers:
    name: Refresh Release Submodules
    runs-on: ubuntu-latest
    outputs:
      container-matrix: ${{ steps.submodules.outputs.containers }}
    steps:
    - uses: actions/checkout@master

    - name: Get docker images for submodules
      id: submodules
      uses: wistefan/get-images-from-submodules@master

  get-releases:
    name: Test releases
    runs-on: ubuntu-latest
    needs: ["get-containers"]

    strategy:
      fail-fast: false
      matrix:
        containers: ${{fromJson(needs.get-containers.outputs.container-matrix)}}

    steps:
      - uses: actions/checkout@v2

      - name: execute check
        run: |
          .github/container-scan.sh ${{ matrix.containers }}
    
   
   
   
