name: "Update Tagged Releases"
on:
  push:

jobs:
  get-containers:
    name: Refresh Release Submodules
    runs-on: ubuntu-latest
    outputs:
      container-matrix: ${{ steps.submodules.outputs.containers }}
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: releases
        submodules: recursive

    - name: Get docker images for submodules
      id: submodules
      uses: wistefan/get-submodules@0.0.2

  get-releases:
    name: Test releases
    runs-on: ubuntu-latest
    needs: ["get-containers"]

    strategy:
      fail-fast: false
      matrix:
        submodules: ${{fromJson(needs.get-containers.outputs.container-matrix)}}

    steps:
    - id: versions
      uses: wistefan/get-releases-by-semver@master
      with:
        versionField: "TAG-NAME"
        repository: ${{ matrix.submodules }}

    - id: print
      run: |
        echo "Releases for ${{ matrix.submodules }}"
        echo "${{steps.versions.outputs.releases}}"
    
   
   
   
