name: "Update Tagged Releases"
on:
  workflow_dispatch:

jobs:
  refresh-modules:
    name: Refresh Release Submodules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: releases
        submodules: recursive
    - name: Merge upstream changes to releases branch
      run: |
        git config --file .gitmodules --get-regexp path | awk '{ print $2 }'
   
